### ISSUE TITLE
BattleInfo Plugin

### ISSUE THREAD

**Issue by Danielosama** [Madmanmayson/KanColleViewer#4]
Hey there,

First of all, I wanted to thank you again for updating KCV, it is by far my favorite viewer and I trembled at the idea of having to use KC3Kai after Phase 2 :x 

Now, I wanted to ask if the BIP works again, since I saw that you updated it in the master branch.

Thanks for all your work.

**Comment by Madmanmayson** [comment]
Yeah I apparently it didn't copy over when I made a release build so I didn't even realize it was broken/missing until a week ago. Right now it mostly works for battles (Event things untested though as I'm only on E1) and will now show the node your at but the IDs and letters don't match up anymore atm. Since my work week just ended my main goal for the next 3 days it to try and get a WebView based version working instead because it will probably be faster then Chromium as it uses Edge instead. I'll also try to get some final fixes going for a new release (that includes BIP).

**Comment by Danielosama** [comment]
Awesome to hear all that :)
Thanks again for all your work and keep it up!
